export const REGISTRATION_REGISTER = 'REGISTRATION_REGISTER';
export const REGISTRATION_UNREGISTER = 'REGISTRATION_UNREGISTER';
export const USER_UNREGISTRED = 'USER_UNREGISTRED';
export const USER_REGISTRED = 'USER_REGISTRED';
