export const REGISTRATION_CREATE = 'REGISTRATION_CREATE';
export const REGISTRATION_DELETE = 'REGISTRATION_DELETE';
export const USER_UNREGISTRED = 'USER_UNREGISTRED';
export const USER_REGISTRED = 'USER_REGISTRED';
